name: calview

dependencies:
     - python=3.13
     - pip
     - pip:
          - pydsstools==3.0
     - numpy=2.4
     - pandas=3.0
     - openpyxl=3.1
     - panel=1.8
     - holoviews=1.22
     - hvplot=0.12
     - bokeh=3.9
     - pyinstaller=6.20
     - rasterio
